### ISSUE TITLE
New peer discovery protocol

### ISSUE THREAD

**Issue by bauerj** [kyuupichan/electrumx#104]
The main reason for a new peer discovery mechanism is that Freenode doesn't want Electrum servers to be on their network.

A simple protocol could look like this:

1. Server `A` wants to join the network and connects to a list of hard-coded servers, including `B`. The JSONRPC interface  could be used for this.
2. Server `A` sends a command like `peer.add` containing information about `A`'s hostname, ports, pruning limit and optionally onion-address to `B` (and all the other servers).
2. Server `B` checks that the hostname it got from `A` resolves to the IP address `A` is connecting from. If it doesn't, it sends an error message. If it does, it responds with a list of all connected peers.
2. `A` continues to connect to the other known peers until it is connected to the whole network.

What do you think?

**Comment by kyuupichan** [comment]
I've been thinking more along the lines of what bitcoind does:

- on startup, you have a hard coded list of servers.  You use this if you have no recent peer history, otherwise you use your own peer history (perhaps mixing in the hard coded servers)
- stored peer history includes things like what is currently on IRC, but also time of last attempted connection, time of last good connection, whether server successfully answered a challenge (e.g. a random UTXO)
- you connect to, and maintain, 8 outgoing peer connections, taken semi-randomly from the DB, but attempting to avoid easy sybil attacks.
- do a peers.subscribe to those 8 servers like the electrum client does, but pass extra args as your own settings, i.e. what is currently on IRC but perhaps also to include ToR.  In ElectrumX I will change peers.subscribe to be a subscription, and it will send notifications of new peers.  If this optional extra argument is passed, it will assume the incoming connection is a server and add it to its peers list.  - add unknown peers to the recent history list, indicating no connection attempts etc. made
- in the background, very occasionally, choose a peer to connect to from your list, and send them a challenge if the connection is successful.  Then disconnect.  Record the results.
- replies to peers.subscribe and new peer notifications: for Electrum clients, should only send for peers that have successfully responded to a challenge (unioned with the hard-coded list?). For peer servers, perhaps we can send immediately, or should we attempt to make a connection?  Perhaps send max 30 known good, max 10 stale or untried ones, randomly selected.
- aged peers in the local history are removed after a certain amount of time (e.g. 30 days) has passed with no successful connection made.

This corresponds roughly to addr (notifications) and getaddr (peers.subscribe).  Challenges can include a random UTXO, header hash request, balance request, etc.

The idea of the challenge is to limit the ability to fill the peer lists with non-servers.

There are a few details I've missed but this is basically it.  It doesn't require any new network messages.

A server should perhaps, occasionally, connect to IRC briefly to get stragglers still using IRC (e-s and jelectrum servers?).  But we should do this less and less, and hopefully someone can implement something similar in e-s and jelectrum too.

Maybe the class implementing this should have a common core that is used by ElectrumX and Electrum client, with a view to the client moving towards becoming a little more independent and less dependent on its main connection.

**Comment by kyuupichan** [comment]
by the way I hope to do some of the above in the next couple of weeks

**Comment by bauerj** [comment]
> Challenges can include a random UTXO, header hash request, balance request, etc. The idea of the challenge is to limit the ability to fill the peer lists with non-servers.

I'm not convinced that would add any security. You could always ask another server for the data.


Also, what is the advantage connecting only to 8 peers?

**Comment by kyuupichan** [comment]
Perhaps we can skip challenges until we see evidence they'd help.

bitcoind does just 8 outgoing connections; I think it's more than enough to maintain a connected set with some basic sybil avoidance
