### ISSUE TITLE
PeerManager coin onion peers are always selected for verifying availability

### ISSUE THREAD

**Issue by fr3aker** [kyuupichan/electrumx#138]
While running with some debugging output for #135 I noticed that coin onion peers are always selected to retry connecting/verify availability. If `tor_proxy.port` is not `None` then `last_tor_retry_time` is never updated.

**Comment by kyuupichan** [comment]
If I understand you correctly you don't have a tor proxy? 

This is all intended behaviour. If you don't have a tor proxy tor peers will have been dropped as they are unreachable. So testing of you've opened a Tor proxy since the last test uses all known for peers from the coin list. The idea of the code is that if you start a tor proxy you shouldn't have to restart electrumx, it will notice itself with occasional retries.

**Comment by fr3aker** [comment]
I do have a tor proxy configured.

**Comment by kyuupichan** [comment]
Ok then tie proxy port is set, and there is no need to keep trying to discover one (the last tor retry time). I'm not really sure what the issue is saying is wrong.

**Comment by fr3aker** [comment]
When you have a tor proxy `last_tor_retry_time` is never updated and stays always `0`.

**Comment by kyuupichan** [comment]
Sure.  Why is that a problem?

**Comment by fr3aker** [comment]
This makes the if at [peers.py#L443](https://github.com/kyuupichan/electrumx/blob/master/server/peers.py#L443) always evaluate to `True`

**Comment by kyuupichan** [comment]
Ah yes that isn't intended.

**Comment by kyuupichan** [comment]
That should probably be testing if your proxy port is None instead. Do you agree? If so please submit a PR and I'll merge it.
