### ISSUE TITLE
A Protocol for Testing?

### ISSUE THREAD

**Issue by stone212** [kyuupichan/electrumx#155]
Is there a good protocol for testing?  I have something that looks good from "# service electrumx status" but I don't see my server in my Electrum client, and I am unable to connect when I enter manually.

Is there a good protocol for testing?  Something between error logs and Layer 7?

Some good RPC commands I can sent to 8000?

Or a way to connect via the HTTP or SSL interface and issue commands?

**Comment by bauerj** [comment]
> Or a way to connect via the HTTP or SSL interface and issue commands?

Sure, you can manually connect to either the TCP or the SSL interface:

    nc $HOST 50001 # for TCP
    openssl s_client -connect $HOST:50002 # for SSL

You can then enter commands for the server. This returns the electrumx version:

    {"id": 0, "method": "server.version", "params": []}

This gives information about the server, for example the public hostname:

    {"id": 0, "method": "server.features", "params": []}

For more commands see https://github.com/kyuupichan/electrumx/blob/master/docs/PROTOCOL.rst

Most likely your issue is either:
 - incorrect configured public hostname
 - incorrect IP to bind on (e.g. `localhost`)
 - a firewall issue

**Comment by stone212** [comment]
Thank you.  I don't know how I missed that.  Tired eyes, late at night I guess.

One question:  What do you mean by "incorrect IP to bind on (e.g. localhost)"?  I don't know what setting you're referring to.  I don't see the word "bind" anywhere on this page for example:
https://github.com/kyuupichan/electrumx/blob/master/docs/ENVIRONMENT.rst

Also, we aren't using a public hostname, just the raw IP address.  But I assume that doesn't matter.

**Comment by stone212** [comment]
For posterity:

I had a blank "HOST" value in the environment file.  I think that's what you meant by "bind" and that solved the problem.  Verified with the test you suggested.  Thank you.
