### ISSUE TITLE
Support for blackcoin?

### ISSUE THREAD

**Issue by followtheart** [kyuupichan/electrumx#171]
Any advice for support for blackcoin?

**Comment by bauerj** [comment]
Yes.

You can add it to [`lib/coins.py`](https://github.com/kyuupichan/electrumx/blob/master/lib/coins.py).

**Comment by followtheart** [comment]
thx,i will have a try.

**Comment by erasmospunk** [comment]
@followtheart @bauerj Blackcoin will not work at the moment because it does not output the block hex with the `getblock` RPC call.

I am currently working on fixing that, check out the `wip` branch [here](https://github.com/erasmospunk/electrumx/tree/wip) and the last coins in lib/coins.py. Blackcoin should be similar, if you want you can make a pull req to my branch and in the end we will merge it here.

**Comment by lateminer** [comment]
@erasmospunk How can I contact you?

**Comment by erasmospunk** [comment]
@lateminer check my email from the commits

Please test this pull request that adds support for blackcoin https://github.com/kyuupichan/electrumx/pull/192

**Comment by kyuupichan** [comment]
I've merged @erasmospunk's changes into master (thanks!).  If someone independently confirms they can sync I will close this issue.

**Comment by followtheart** [comment]
@erasmospunk Good job!
@kyuupichan It works.
