### ISSUE TITLE
chunk indices not advancing (on BCH netwrok)

### ISSUE THREAD

**Issue by ffallah** [kyuupichan/electrumx#235]
I am receiving this message frequently in electrumx log:
`chunk indices not advancing (wrong network?): [232, 231, 230]`

Here is my config:

export DB_DIRECTORY=/data/bitcoin-cash/electrumx/db
export DAEMON_URL=http://x:x@localhost:28332/
export SSL_CERTFILE=/data/bitcoin/electrumx/server.crt
export SSL_KEYFILE=/data/bitcoin/electrumx/server.key
export TCP_PORT=50011
export SSL_PORT=50012
export HOST=electrumx-bch.adminsehow.com
export IRC=true
export IRC_NICK=adminsehow
export REPORT_TCP_PORT_TOR=0
export REPORT_SSL_PORT_TOR=0
export REPORT_HOST=electrumx-bch.adminsehow.com
export DONATION_ADDRESS=1BcxFxxqfFY7ezzWWCq9aHXaxKEhEPft5X

NET is not set, so it should default to mainnet.

**Comment by notr1ch** [comment]
I'm also seeing this. I believe this is caused by BCH and BTC peers getting mixed up somewhere, so BTC electrum clients end up connecting to BCH electrumx servers. I believe these are coming from BCH electrum servers having BCH peers cached, or Electrum client caches.

I checked the hardcoded BCH peer list and the network of peers from those, and they are all valid BCH servers at the current time.

**Comment by kyuupichan** [comment]
This is a client-side issue.  Which client and why is hard to determine.
