### ISSUE TITLE
Segwit and Bech32 addresses

### ISSUE THREAD

**Issue by thehobbit85** [kyuupichan/electrumx#294]
Is there a plan on supporting native segwit addresses in bech32 format?

**Comment by kyuupichan** [comment]
Not in ElectrumX; it doesn't care.  Addresses are a GUI thing.

**Comment by thehobbit85** [comment]
What do you mean it doesn't care?
When I use any of the blockchain.address functions I should be able to pass in the new bech32 format addresses.
{ "id": 6, "method":"blockchain.address.subscribe", "params": ["1NS17iag9jJgTHD1VXjvLCEnZuQ3rJDE9L"] }
works but:
{ "id": 6, "method":"blockchain.address.subscribe", "params": ["bc1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3qccfmv3"] }
or 
{ "id": 6, "method":"blockchain.address.subscribe", "params": ["bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4"] }
 doesn't

**Comment by kyuupichan** [comment]
You should use the scripthash and subscribe to that instead

**Comment by thehobbit85** [comment]
I could if I wanted P2SH addresses but what if I want native segwit formats (P2WPKH, P2WSH)?
As far as I know, bip173 (https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) determines that support for native Segwit addresses will be only in the bech32 format

**Comment by kyuupichan** [comment]
You need to subscribe to the script. That is what electrum will do. Addresses are a user interface thing in the wallets.

**Comment by thehobbit85** [comment]
I don't understand what is difference between supporting base58 and bech32?
Currently I can use a base58 addresses to subscribe and not the full P2PKH/P2SH scripts so what is the difference?

**Comment by kyuupichan** [comment]
The difference is that address.subscribe is obsolete and will one day be removed.

You must subscribe by the hash of the bitcoin script that pays you.

**Comment by thehobbit85** [comment]
Oh, great to know that. I will change code to support that.
So only script.subscribe from now on?

**Comment by kyuupichan** [comment]
blockchain.address.subscribe will work for at least a year I guess.  But only for original 1- and 3- style addresses.

blockchain.scripthash.subscribe will work now for those kinds of addresses (but with the script hash instead of the address) and for any other kind of script, including segwit ones.

I believe Electrum git HEAD is using blockchain.scripthash.subscribe; you might want to check there if unsure.  ElectrumX effectively converts an address subscribe to a scripthash subscribe internally, so you can look at its code too.

**Comment by thehobbit85** [comment]
That is really good to know.
Is there any official documentation for it?

**Comment by bauerj** [comment]
There is https://github.com/kyuupichan/electrumx/blob/master/docs/PROTOCOL.rst#blockchainscripthashsubscribe

**Comment by thehobbit85** [comment]
from what I can see from here:
https://github.com/kyuupichan/electrumx/blob/08b80b93068c8428b68fb71297702c3b7c8d8a36/server/session.py
It has not been implemented yet.

So for now I can't use P2WH/P2WPKH at all?

**Comment by kyuupichan** [comment]
I'm starting to lose hope for this conversation.  The server is complete.  You either misunderstand addresses, scripting, or the protocol.  I have no idea where the issue lies.

**Comment by thehobbit85** [comment]
Why lose hope? I just didn't see line 428.

**Comment by youssefgh** [comment]
@thehobbit85 Since electrumx support searching by scripthash, you can search for infos related to Bech32 by converting the address to scripthash.
The term scripthash is a little bit confusing here. you can think of it like the locking script
It will help a lot if you take a look at how Electrum wallet interact with the this API

**Comment by youssefgh** [comment]
@thehobbit85 Since electrumx support searching by scripthash, you can search for infos related to Bech32 by converting the address to scripthash.
The term scripthash is a little bit confusing here. you can think of it like the locking script
It will help a lot if you take a look at how Electrum wallet interact with the this API
