### ISSUE TITLE
Reorg / 'Block not found' with Bitcoin testnet

### ISSUE THREAD

**Issue by benma** [kyuupichan/electrumx#315]
Hi

I have been successfully running electrumx for bitcoin testnet like this in the past weeks:

RPC_PORT=8002 PEER_DISCOVERY= TCP_PORT=51001 DB_DIRECTORY=~/.electrumx-testnet DAEMON_URL="...@127.0.0.1" COIN=BitcoinSegwit NET=testnet /path/to/electrumx_server.py

Running it today, this happened:

```
INFO:Prefetcher:catching up to daemon height 1,230,660 (283 blocks behind)
INFO:BlockProcessor:chain reorg detected
INFO:BlockProcessor:chain was reorganised replacing 1 block at heights 1,230,377-1,230,377
ERROR:Controller:Traceback (most recent call last):
  File "/home/marko/coding/electrumx/server/controller.py", line 177, in on_future_done
    future.result()
  File "/home/marko/coding/electrumx/server/block_processor.py", line 206, in main_loop
    await task()
  File "/home/marko/coding/electrumx/server/block_processor.py", line 257, in check_and_advance_blocks
    await self.reorg_chain()
  File "/home/marko/coding/electrumx/server/block_processor.py", line 293, in reorg_chain
    blocks = await self.daemon.raw_blocks(hex_hashes)
  File "/home/marko/coding/electrumx/server/daemon.py", line 240, in raw_blocks
    blocks = await self._send_vector('getblock', params_iterable)
  File "/home/marko/coding/electrumx/server/daemon.py", line 197, in _send_vector
    return await self._send(payload, processor)
  File "/home/marko/coding/electrumx/server/daemon.py", line 132, in _send
    result = processor(result)
  File "/home/marko/coding/electrumx/server/daemon.py", line 192, in processor
    raise DaemonError(errs)
server.daemon.DaemonError: [{'code': -5, 'message': 'Block not found'}]
```

It is stuck at that point. 

Edit: deleting the database and syncing from scratch fixed it for now, but this bug should still be looked into. It would be a problem if the same happened on mainnet.

**Comment by kyuupichan** [comment]
Did you change the COIN or bitcoind whilst doing this?

The only time I have seen this happen is when the bitcoind you are using considers the block ElectrumX is trying to reverse invalid.  This happened for example at the Bitcoin Cash fork if you followed one chain and then tried to switch bitcoind to the other chain.

As to your question, the only solution is to rebuild your DB from scratch, sorry.  At one stage I was considering storing recent blocks in the ElectrumX DB so that this didn't happen, but I never got around to implementing it.

**Comment by benma** [comment]
Thanks for the swift response.

> Did you change the COIN or bitcoind whilst doing this?

No, I haven't.

**Comment by erasmospunk** [comment]
@kyuupichan this is a general problem with various coins (older codebases) where you cannot get the coinbase transaction from an orphan block as it is not indexed (so I run patched versions). Another (rare) scenario is when you have 2 daemons and when switching the other node is on a different chain.

A solution could be storing a `REORG_LIMIT` number of latest blocks and using those then reorging instead of asking the daemon. The blocks could be saved as files, with the block height as the filename and be regularly deleted every time the blockchain advances.

**Comment by kyuupichan** [comment]
@erasmospunk yes I will get around to storing recent blocks at some stage.  I've not had much time to work on ElectrumX recently; hopefully this will change.  I have a lot of things I want to do...

**Comment by london2103** [comment]
Any update relate to this ?
electrumx_server.py[11434]:     transactions = await self.getrawtransactions(b.get('tx'), False)
electrumx_server.py[11434]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 241, in getrawtransactions
electrumx_server.py[11434]:     replace_errs=replace_errs)
electrumx_server.py[11434]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 194, in _send_vector
electrumx_server.py[11434]:     return await self._send(payload, processor)
electrumx_server.py[11434]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 129, in _send
electrumx_server.py[11434]:     result = processor(result)
electrumx_server.py[11434]:   File "/usr/local/lib/python3.6/dist-packages/electrumx-1.1-py3.6.egg/server/daemon.py", line 189, in processor
electrumx_server.py[11434]:     raise DaemonError(errs)
electrumx_server.py[11434]: server.daemon.DaemonError: [{'code': -5, 'message': 'No information available about transaction'}, {'code': -5, 'message': 'No information available about transaction'}]
