### ISSUE TITLE
Looking for guide on adding altcoin

### ISSUE THREAD

**Issue by karlinnolabs** [kyuupichan/electrumx#363]
I'm not sure where I'd get the following values from my alt coin 

    XPUB_VERBYTES = bytes.fromhex("???")
    XPRV_VERBYTES = bytes.fromhex("???")
    P2PKH_VERBYTE = bytes.fromhex("??")
    P2SH_VERBYTES = [bytes.fromhex("??"), bytes.fromhex("??")]
    WIF_BYTE = bytes.fromhex("??")

Are these related to the pub/private keys for the genesis coin base?

**Comment by erasmospunk** [comment]
Usually this is found in [chainparams.cpp](https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp#L139) in newer codebases.

Having said that, this is not a place to open question tickets.

**Comment by kyuupichan** [comment]
Read about Base58 encoding.

**Comment by karlinnolabs** [comment]
I've spent plenty of time learning about base58 encoding, but the issue I'm having is identifying the correct numbers - potentially using something which is named similarly would help here, or at least a comment explaining where to find the values.

**Comment by lclc** [comment]
Check the chainparams of e.g. Litecoin, see how it's converted, to the same for your coin.

**Comment by karlinnolabs** [comment]
@lclc I did that, I found that these lines in litecoin 

base58Prefixes[EXT_PUBLIC_KEY] = boost::assign::list_of(0x04)(0x88)(0xB2)(0x1E).convert_to_container<std::vector<unsigned char> >();
        base58Prefixes[EXT_SECRET_KEY] = boost::assign::list_of(0x04)(0x88)(0xAD)(0xE4).convert_to_container<std::vector<unsigned char> >();

Don't match these params in electrum-x


    XPUB_VERBYTES = bytes.fromhex("019d9cfe")
    XPRV_VERBYTES = bytes.fromhex("019da462")

So you see where my confusion comes from.

**Comment by 2lazy2debug** [comment]
Your xpub would just be 0488B21E , just concatenate your bytes

**Comment by develCuy** [comment]
@kyuupichan the problem is not lack of documentation but Klingon. I can guess that VERBYTES stand for version bytes. But how in the world would I realize that XPUB stands for EXT_PUBLIC_KEY, that XPRV stands for EXT_SECRET_KEY? How about P2PKH also named "legacy" and P2SH not adopted in every altcoin? If you guys create your own Klingon, please document it.

@karlinnolabs and everyone looking to fork your own ElectrumX, please document here:

https://en.bitcoin.it/wiki/Pay_to_script_hash
https://en.bitcoin.it/wiki/List_of_address_prefixes

And do be master jerks, just be masters.
