### ISSUE TITLE
source-destination mismatch vs TOR_PROXY_HOST

### ISSUE THREAD

**Issue by shsmith** [kyuupichan/electrumx#601]
192.168.69.103 is my TOR_PROXY_HOST.
Should this IP be exempt from source-destination verification?
```
WARNING:PeerManager:rejected add_peer request from 192.168.69.103 for electrum.freepages.dk (source-destination mismatch)

WARNING:PeerManager:rejected add_peer request from 192.168.69.103 for electroncash.dk (source-destination mismatch)
```

**Comment by kyuupichan** [comment]
Is this a new problem?  What is your config?

**Comment by shsmith** [comment]
I think it has been happening for some time.  
It only happens on incoming peers (the message is not seen on launch when all the outgoing verifications happen).

If it matters I am using a hostname, not an IP in the TOR_PROXY_HOST environment. 
It looks like this:
`TOR_PROXY_HOST=torserver.lan`

Here is another example:
```
INFO:PeerManager:accepted add_peer request from 94.130.147.211 for bitcoin-node.org
INFO:PeerManager:accepted new peer bitcoin-node.org from 94.130.147.211
WARNING:PeerManager:rejected add_peer request from 192.168.69.103 for bitcoin-node.org (source-destination mismatch)
INFO:PeerManager:[bitcoin-node.org:1 SSL] task timed out after 30s
INFO:PeerManager:forgetting unreachable peer: bitcoin-node.org

```
I do not see bitcoin-node.org or 94.130.147.211 in my peers list.
Maybe the problem is on the other end?

**Comment by SomberNight** [comment]
Isn't this the same as https://github.com/kyuupichan/electrumx/issues/257 ?

**Comment by kyuupichan** [comment]
@shsmith why are non-tor peers trying to connect to you through your tor proxy?

**Comment by shsmith** [comment]
> @shsmith why are non-tor peers trying to connect to you through your tor proxy?

Likely is not on purpose. Maybe they have the FORCE_PROXY environment. I can't think of any good use case for FORCE_PROXY without also REPORT_HOST_TOR.

**Comment by kyuupichan** [comment]
@shsmith @SomberNight I can require either or both of these if FORCE_PROXY:

* REPORT_HOST_TOR be set
* REPORT_HOST be unset

What should be done to close this issue?

**Comment by SomberNight** [comment]
> why are non-tor peers trying to connect to you through your tor proxy?

Servers try to connect and verify all peers they get to know about, both clearnet and .onion.
The Tor proxy just happens to be on the same local IP as where the hidden service is hosted; this is probably a common configuration (I have the same): there is only one Tor process, and you use it for both outgoing connections (proxy) and incoming (hidden service).

> I can require either or both of these if FORCE_PROXY:
REPORT_HOST_TOR be set
REPORT_HOST be unset

Would either of those options allow a clearnet peer to add itself though?

Let's say Alice runs a server with
- REPORT_HOST_TOR set
- REPORT_HOST unset
- FORCE_PROXY does not matter

Bob has a clearnet only server. Can Bob get his server added to Alice's list?
When Bob tries, Alice will get `source-destination mismatch` in her log; but maybe this is fine.

AFAICT, if Alice runs a Tor-only server, only other .onion servers can add themselves. Alice's server will also ask already known peers about their peers (`server.peers.subscribe`) and these include the default server list, so the onion servers will not get partitioned.

-----

> I can require either or both of these if FORCE_PROXY:
REPORT_HOST be unset

With `FORCE_PROXY` enabled, a server cannot register (`server.add_peer`) its clearnet host on other servers, so that requirement might make some sense. Although, it can register its onion host, and then others can ask its peer list (`server.peers.subscribe`) and then it can report the clearnet host that then can be verified... soooooo
I guess we could just leave everything as is, and close this.

**Comment by kyuupichan** [comment]
@SomberNight thanks for the reply.  

> Bob has a clearnet only server. Can Bob get his server added to Alice's list?
When Bob tries, Alice will get source-destination mismatch in her log; but maybe this is fine.

Bob is clearnet only so has no way of advertising to Alice who is only offers incoming Tor connections.  However if Alice finds out about Bob some other way, such as from another peer's list, when she connects to him to verify through her Tor proxy but to the clearnet, why would she get source-destination mismatch?  I guess that would happen if DNS resolution is left to the proxy right?

Smoothly supporting Tor is a bit tricky; I guess we should wait until someone lists out sane setups we want to support, what current issues are with each (if any), and comes up with a plan to provide a way for a server admin to configure it and support it in ElectrumX
