### ISSUE TITLE
"electrumx_rpc.py disconnect <ID>" doesn't seem to work.

### ISSUE THREAD

**Issue by tunkaflux** [kyuupichan/electrumx#62]
I'm trying to disconnect the sessions with client "Send 0.006886BTC to 1CyNqxEVrej8Mup1FJtBSsRZMyz5SyMmnN to stop atack plox".
What I did yesterday was: 
```
electrumx/electrumx_rpc.py sessions  | grep plox | cut -d" " -f 1 | tr '\n' '\0\' | xargs -0 -I % electrumx/electrumx_rpc.py disconnect %
```
which shows the disconnected message for all IDs I feed to electrum_rpc.py. However, now, almost 24 hours later, the sessions are still there.

I'll try and get a sample for today.

**Comment by shsmith** [comment]
I did the same thing and all the closed sessions went into the "C" (closing) state, but 90 minutes later they were still there. I eventually had to kill the process to get rid of them. Seems like there should be some timeout in the graceful close process. Can we forcibly reset the socket or something?

**Comment by kyuupichan** [comment]
Can you both confirm that it is only some connections that are stubborn - i.e. that the functionality does work as expected for some connections?

**Comment by shsmith** [comment]
Yes, in my case I tried closing all connections (about 700) and after a few minutes the session count was down to about 80, but those 80 were "stubborn" and never went away.  

When I closed all connections it was because I saw memory usage growing and I suspected an out-of-memory kill was coming soon. I was expecting to see usage drop when the offending client was dropped.  With just those stuck connections, the memory usage was still high (about 1.5 GB). Not sure if that is related or not.

**Comment by kyuupichan** [comment]
This might be better in 0.8.8.  In fact, I think it might be too agressive, and I should only shutdown the socket after giving it some grace period.  Anyway, if you can tell me if 0.8.8 works better I can work on putting a grace period of say 5 seconds.
