### ISSUE TITLE
For those who got stuck with ports not opening (tcp, ssl)

### ISSUE THREAD

**Issue by xianglo** [kyuupichan/electrumx#913]
Dont forget to prepend your ports in electrumx.conf with "SERVICES=" like so:

SERVICES=tcp://:50001,ssl://:50002
This is NOT clear in the docs for the less experienced. Lots of headache saved.

**Comment by maltokyo** [comment]
Adding this seems optional, as for me port 50002 is open, even without that line.  Maybe it is open by default, as otherwise, electrumx is quite useless.  Is it not opened for you automatically?

**Comment by kyuupichan** [comment]
I've improved the docs here; it is documented properly but perhaps easy to miss

**Comment by leshacat** [comment]
@kyuupichan no , it still is an issue. The default config even still has TCP_PORT in it and causes daemon to fail on first start.

Please update the default config and the documentation better to show an example of the new config because I never saw one and had to google for hours to find the "documentation" you speak of which doesn't even give an example of the new SERVICES line even though it shows examples of other lines.

Also after updating the line to the new SERVICES line I still have 0 TCP port opening.

```
# default /etc/electrumx.conf for systemd

# REQUIRED
DB_DIRECTORY = /db/pexa
# Bitcoin Node RPC Credentials
DAEMON_URL = http://hiddenuser:HIDDENPASSWORD@192.168.1.10:4351/

COIN = Bitcoin
NET = mainnet

# See http://electrumx.readthedocs.io/en/latest/environment.html for
# information about other configuration settings you probably want to consider.

#SSL_CERTFILE=/etc/electrumx/server.crt
#SSL_KEYFILE=/etc/electrumx/server.key
#TCP_PORT=5001
#SSL_PORT=50002
# Listen on all interfaces:
HOST=

SERVICES = tcp://192.168.1.11:5001,rpc://0.0.0.0:2401
```
